# -*- coding: utf-8 -*-
"""case study1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eHYSDYMpmTnef4oALi0WfAhCDwpfB9_
"""

#  Import data Manipulation  Library
import numpy as np
import pandas as pd

# Import Dta Visualization Library
import seaborn as sns
import matplotlib.pyplot as plt

# Import FilterWarning Library
#import warnings
#warnings.filterwarnings('ignore')
# Import Data Loging
#import logging
#logging.basicConfig(level=logging.INFO,
#                   filename= 'app.log',
#                  filemade = 'w',
#                 format = "%(asctime)s %(levelname)s %(message)s")

# import Data Using Pandas Function

url = 'https://raw.githubusercontent.com/chandanc5525/Dataset/refs/heads/main/Data/titanic_train.csv'

data = pd.read_csv(url)
data.sample(frac = 1)

# Understanding data Information
data.info()

# Identify Passanger Class based on Category
data['Pclass'].value_counts()

# Distribution of Passanger Class based on Category
data['Pclass'].value_counts().plot(kind = 'pie',autopct = '%.2f',explode = [0.01,0.01,0.01],figsize = (5,5))
plt.title('Pessanger Class Distribution')
plt.legend(['First Class','Second Class','Third Class'])
plt.show()

# Distribution of Passanger Class based on Category
data['Parch'].value_counts().plot(kind = 'barh',figsize = (5,5))
plt.title('Pessanger Class Distribution')
plt.show()

# Distribution of Passanger Class based on Category
data['Embarked'].value_counts().plot(kind = 'pie',autopct = '%.2f',explode= [0.01,0.01,0.01],figsize = (5,5))
plt.title('Pessanger Board Ther Journey')
plt.show()

"""Data Insight:
the given dataset  12 column and 891 rows out of each
comuln name age and cabin as missing valuse and stategis can be disided based on above database
1. if the column cantent more than 5 % of mising values then the implutation done by the help of mideun
2. for cabin we find more volue we can draw the file
3. the dataset also shows 55.11% passengers belong to class 3 , 22.65% passengers belong to class 2 and 24.24% passengers belongs to class 1
4. its was found that 72.44 passenger board from s(Southampton) , 8.66% passengers board from Q(Queenstown) and 18.90% passenger Board from C

"""

Southampton = data[data['Embarked'] == 'S']
print(Southampton)

Southampton['Survived'].value_counts(),Southampton['Sex'].value_counts()

Southampton[Southampton['Sex'] == 'male']['Survived'].value_counts()

Southampton['Age'].mean()

Southampton[Southampton['Sex'] == 'female']['Survived'].value_counts()

Queenstown = data[data['Embarked'] == 'Q']
print(Queenstown)

Queenstown['Survived'].value_counts(),Southampton['Sex'].value_counts()

Queenstown[Queenstown['Sex'] == 'male']['Survived'].value_counts()

Queenstown[Queenstown['Sex'] == 'female']['Survived'].value_counts()

Queenstown['Age'].mean()

Cherbourg = data[data['Embarked'] == 'C']
print(Cherbourg)

Cherbourg['Survived'].value_counts(),Cherbourg['Sex'].value_counts()

Cherbourg[Cherbourg['Sex'] == 'male']['Survived'].value_counts()

Cherbourg[Cherbourg['Sex'] == 'male']['Survived'].value_counts()

Cherbourg['Age'].mean()

data[data['Pclass'] == 1]['Survived'].value_counts()

data[data['Pclass'] == 2]['Survived'].value_counts()

data[data['Pclass'] == 3]['Survived'].value_counts()

